# Generated by Django 3.0.7 on 2021-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostgroup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfomanage',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='hostinfomanage',
            name='hostaddress',
        ),
        migrations.RemoveField(
            model_name='hostinfomanage',
            name='hostport',
        ),
        migrations.RemoveField(
            model_name='hostinfomanage',
            name='visitproof',
        ),
        migrations.AddField(
            model_name='hostinfomanage',
            name='credential',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='访问凭证'),
        ),
        migrations.AddField(
            model_name='hostinfomanage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述信息'),
        ),
        migrations.AddField(
            model_name='hostinfomanage',
            name='hostip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='主机地址'),
        ),
        migrations.AddField(
            model_name='hostinfomanage',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='主机端口'),
        ),
    ]
