# Generated by Django 3.0.7 on 2021-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostgroup', '0002_auto_20210617_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问凭证')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用于ssh的用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='用于ssh的密码')),
                ('become_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='当需要特权时是su或者enable')),
                ('become_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='当需要特权时 使用的用户名')),
                ('become_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='当需要特权时 使用的密码')),
                ('public_key', models.TextField(blank=True, null=True, verbose_name='公钥认证')),
            ],
            options={
                'verbose_name': '主机用户管理模型',
                'verbose_name_plural': '主机用户管理模型',
                'db_table': 'host_user_manage',
            },
        ),
    ]
