# Generated by Django 3.0.7 on 2021-06-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfoManage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机名称')),
                ('hostgroup', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机组')),
                ('hostaddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机地址')),
                ('hostport', models.IntegerField(blank=True, null=True, verbose_name='主机端口')),
                ('visitproof', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问凭证')),
                ('describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述信息')),
                ('hoststatus', models.IntegerField(blank=True, null=True, verbose_name='主机状态')),
            ],
            options={
                'verbose_name': '主机管理模型',
                'verbose_name_plural': '主机管理模型',
                'db_table': 'host_info_manage',
            },
        ),
    ]
