# Generated by Django 3.0.7 on 2021-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases_Migration_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='任务id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('db_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='源数据库地址ip')),
                ('db_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='源数据库用户名')),
                ('db_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='源数据库用户密码')),
                ('db_port', models.IntegerField(blank=True, null=True, verbose_name='源数据库端口')),
                ('db_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='源数据库库名')),
                ('db_tablename', models.TextField(blank=True, null=True, verbose_name='数据库需要操作的列表')),
                ('filepath', models.CharField(blank=True, max_length=255, null=True, verbose_name='生成文件的地址')),
                ('db_ip_lg', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标数据库ip')),
                ('db_username_lg', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标数据库用户')),
                ('db_password_lg', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标数据库用户密码')),
                ('db_port_lg', models.IntegerField(blank=True, null=True, verbose_name='目标数据库端口')),
                ('db_name_lg', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标数据库库名')),
            ],
            options={
                'verbose_name': '数据迁移任务表',
                'verbose_name_plural': '数据迁移任务表',
                'db_table': 'data_migration_task',
            },
        ),
        migrations.CreateModel(
            name='File_Migration_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='任务id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('source_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='源服务器ip')),
                ('source_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='源服务器用户名')),
                ('source_pwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='源服务器用户密码')),
                ('source_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='源服务器文件地址')),
                ('interval_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='时间间隔')),
                ('date_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='时间类型 1:月份 2:天数')),
                ('long_range_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标服务器ip')),
                ('long_range_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标服务器用户')),
                ('long_range_pwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标服务器用户密码')),
                ('backups_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标服务器备份文件存放地址')),
            ],
            options={
                'verbose_name': '文件迁移任务表',
                'verbose_name_plural': '文件迁移任务表',
                'db_table': 'file_migration_task',
            },
        ),
        migrations.CreateModel(
            name='Implement_Status_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField(blank=True, null=True, verbose_name='迁移信息id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('task_type', models.IntegerField(blank=True, null=True, verbose_name='操作类型 1:数据库 2:文件')),
                ('task_status', models.IntegerField(blank=True, null=True, verbose_name='执行状态')),
                ('task_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='中文说明')),
            ],
            options={
                'verbose_name': '任务执行状态表',
                'verbose_name_plural': '任务执行状态表',
                'db_table': 'implement_status_task',
            },
        ),
    ]
