# Generated by Django 3.0.7 on 2021-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatization', '0002_databases_migration_task_file_migration_task_implement_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases_migration_task',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='任务id'),
        ),
        migrations.AlterField(
            model_name='file_migration_task',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='任务id'),
        ),
        migrations.AlterField(
            model_name='implement_status_task',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='迁移任务id'),
        ),
    ]
