# Generated by Django 3.0.7 on 2021-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatization', '0003_auto_20210609_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implement_status_task',
            name='job_id',
        ),
        migrations.AddField(
            model_name='implement_status_task',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='迁移任务id'),
        ),
    ]
