# Generated by Django 3.0.7 on 2021-06-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatization', '0004_auto_20210609_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='implement_status_task',
            name='task_imp_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='时间间隔类型 0:不启用该间隔 1:秒 2:分 3:小时'),
        ),
        migrations.AddField(
            model_name='implement_status_task',
            name='task_imp_operation',
            field=models.IntegerField(blank=True, null=True, verbose_name='任务操作类型 1:时间间隔 2:时间点 3:corn'),
        ),
        migrations.AddField(
            model_name='implement_status_task',
            name='task_imp_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='具体的间隔数或时间点'),
        ),
    ]
