# Generated by Django 3.0.7 on 2021-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatization', '0005_auto_20210609_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostInfoManage',
        ),
        migrations.AddField(
            model_name='file_migration_task',
            name='lcoal_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='本地中转地址'),
        ),
    ]
