# Generated by Django 3.0.7 on 2021-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatization', '0006_auto_20210609_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_migration_task',
            name='lcoal_path',
        ),
        migrations.AddField(
            model_name='file_migration_task',
            name='local_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='本地中转地址'),
        ),
    ]
