# Generated by Django 3.0.7 on 2021-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatization', '0007_auto_20210609_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases_migration_task',
            name='task_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='file_migration_task',
            name='task_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='任务类型'),
        ),
    ]
